dw_dbt_preco_commodities:
    target: dev
    outputs:
        dev:
            type: postgres
            host: "{{ env_var('DB_PROD_HOST') }}"
            port: "{{ env_var('DB_PROD_PORT') }}"
            dbname: "{{ env_var('DB_PROD_NAME') }}"
            schema: "{{ env_var('DB_PROD_SCHEMA') }}"
            user: "{{ env_var('DB_PROD_USER') }}"
            pass: "{{ env_var('DB_PROD_PASS') }}"
            threads: "{{ env_var('DB_PROD_THREADS') }}"
            keepalives_idle: 0
