dw_dbt_preco_commodities:
    target: dev
    outputs:
        dev:
            type: postgres
            host: "{{ env_var('DB_HOST') }}"
            port: "{{ env_var('DB_PORT') | int }}"
            dbname: "{{ env_var('DB_NAME') }}"
            schema: "{{ env_var('DB_SCHEMA') }}"
            user: "{{ env_var('DB_USER') }}"
            pass: "{{ env_var('DB_PASS') }}"
            threads: "{{ env_var('DB_THREADS') | int }}"
            keepalives_idle: 0
